'use client';
import {lazy,Suspense,useEffect,useRef,useState}from'react';
import {Tabs,TabsList,TabsTrigger,TabsContent}from'@/components/ui/tabs';
import {Switch}from'@/components/ui/switch';
import {Slider}from'@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from'@/components/ui/select';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose}from'@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow}from'@/components/ui/table';
import {ArrowUpRight,ArrowDown,Play,Pause,RotateCcw,Maximize2,BookOpen,SlidersHorizontal,ChevronRight,ChevronsLeft,ChevronsRight}from'lucide-react';
// Load the browser renderer only after teaching data arrives in a client effect.
// Importing Three.js during Worker startup can invoke forbidden global operations.
const AnatomyViewer=lazy(()=>import('./AnatomyViewer')); 
import{modes,organNames,targetNames,type Atlas,type Teaching,type Mode,type Layers}from'./model-types';
const initialLayers:Layers={Anatomy:true,CellTypes:true,Hormones:true,Targets:true,Annotations:true};
const notes:Record<Mode,{title:string;body:string;note:string}>={
 ANATOMY:{title:'The anatomy',body:'Inspect the stomach, duodenum, jejunum, ileum and detailed colon. Drag to rotate. Select a region to isolate it.',note:'Try the side view.'},
 ALL:{title:'Where the cells are',body:'K cells are enriched proximally. L-cell density increases toward the ileum and colon. The four L-cell peptides share one marker field.',note:'Density is a gradient.'},
 ATLAS:{title:'Sources & targets',body:'Select a hormone to reveal its source cells, every target connection and the traveling signal. Target organs appear as schematic insets.',note:'Follow the colored path.'},
 MECHANISM:{title:'From lumen to target',body:'A luminal cue reaches an enteroendocrine cell. The cell activates, releases a signal from its basal side, and a target responds. Nutrient sensing differs across cell types and nutrients.',note:'Sense. Release. Respond.'},
 LOCAL:{title:'Local signaling',body:'Somatostatin inhibits neighboring secretory cells. Serotonin participates in local and enteric-neural signaling. Neither is shown here as a generic meal response.',note:'A signal can act nearby.'},
 FASTING:{title:'Between meals',body:'Follow the motilin-associated MMC wavefront alongside the fundic ghrelin pathway to the brain. The wave illustrates migrating motor activity, not a food bolus.',note:'No meal cue in this view.'},
 COMPARE:{title:'The incretin effect',body:'Plasma glucose is matched between oral and IV delivery. The larger oral insulin response illustrates the incretin contribution of GIP and GLP-1.',note:'Same glucose. More insulin.'}};
const cellNames:Record<string,string>={K:'K cells',L:'L cells',I:'I cells',S:'S cells',G:'G cells','P/D1':'P/D1 cells',D:'D cells',M:'M cells',Enterochromaffin:'Enterochromaffin'};
import {glpJourney} from './meal-lesson';
import MealCheck from './MealCheck';
function Sources(){return <Dialog><DialogTrigger className="text-link"><BookOpen size={16}/> Sources & limitations</DialogTrigger><DialogContent className="sources-dialog"><DialogTitle>Sources & model limitations</DialogTitle><DialogDescription>References used for the anatomy and teaching sequences.</DialogDescription><div className="sources-body"><p>The approved Blender anatomy, target insets and animation tracks are retained. Web lighting differs from Blender’s rendered lighting.</p><ul><li><a href="https://openstax.org/books/anatomy-and-physiology-2e/pages/23-4-the-stomach" target="_blank" rel="noreferrer">OpenStax — The stomach ↗</a></li><li><a href="https://openstax.org/books/anatomy-and-physiology/pages/23-5-the-small-and-large-intestines" target="_blank" rel="noreferrer">OpenStax — Small and large intestines ↗</a></li><li><a href="https://www.ncbi.nlm.nih.gov/books/NBK543806/" target="_blank" rel="noreferrer">IDKD — Small bowel anatomy ↗</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/26876794/" target="_blank" rel="noreferrer">Nauck & Meier — Incretin physiology ↗</a></li><li><a href="https://pubmed.ncbi.nlm.nih.gov/22450306/" target="_blank" rel="noreferrer">Deloose et al. — Migrating motor complex ↗</a></li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7098877/" target="_blank" rel="noreferrer">GLP-2 and indirect mucosal signaling ↗</a></li></ul><h3>What is simplified</h3><p>External GI anatomy with compressed bowel length; no mesentery, omenta, vessels or internal mucosa. Target insets are schematic and are not placed at their anatomical coordinates.</p><p>Surface markers locate epithelial populations. Their size and density are qualitative, not histological positions or measured counts. Shared L-cell markers do not imply identical coexpression in every cell.</p><p>Connections show functional relationships, including indirect and neural pathways. GLP-2 mucosal effects include indirect actions. The mechanism shows a representative target; the full role description may involve other targets. Timing, response pulses and oral/IV curves are conceptual, not measured physiology. The MMC overlay is not a biomechanical simulation.</p><h3>Photography</h3><p><a href="https://unsplash.com/photos/cooked-food-on-plate-_Buh5P_61JE" target="_blank" rel="noreferrer">Meal photograph — Ella Olsson / Unsplash</a>, cropped under the Unsplash License.</p><p><a href="https://commons.wikimedia.org/wiki/File:Normal_Small_Intestine_Mucosa_(5916217283).jpg" target="_blank" rel="noreferrer">Normal small-intestinal mucosa — Ed Uthman</a>, cropped, <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noreferrer">CC BY 2.0</a>. Villi are visible; hormone-specific cells are not identified.</p></div></DialogContent></Dialog>}
export default function Home(){
 const[atlas,setAtlas]=useState<Atlas|null>(null),[teaching,setTeaching]=useState<Teaching|null>(null),[error,setError]=useState(false),[ready,setReady]=useState(false);
 const[mode,setMode]=useState<Mode>('MECHANISM'),[hormone,setHormone]=useState('GLP1'),[organ,setOrgan]=useState('all'),[view,setView]=useState('front'),[layers,setLayers]=useState<Layers>(initialLayers),[frame,setFrame]=useState(1),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1'),[loop,setLoop]=useState(true),[layerPanel,setLayerPanel]=useState(false);
 const[textMode,setTextMode]=useState(false),[modelError,setModelError]=useState('');
 const openReading=()=>{setPlaying(false);setReady(false);setTextMode(true)};
 const retryModel=()=>{setModelError('');setReady(false);setTextMode(false)};
 const scrollToModel=()=>{const model=document.querySelector<HTMLElement>('#model');model?.focus({preventScroll:true});model?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};
 const frameRef=useRef(frame);frameRef.current=frame;
 useEffect(()=>{Promise.all([fetch('/assets/atlas.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/assets/teaching.json').then(r=>{if(!r.ok)throw Error();return r.json()})]).then(([a,t])=>{setAtlas(a as Atlas);setTeaching(t as Teaching)}).catch(()=>setError(true))},[]);
 useEffect(()=>{if(!playing)return;let last=0,id=0;const tick=(t:number)=>{if(last){const next=frameRef.current+Math.min(t-last,100)*24*Number(speed)/1000;if(next>=180){if(loop)setFrame(1+(next-180));else{setFrame(180);setPlaying(false);return}}else setFrame(next)}last=t;id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[playing,speed,loop]);
 const setTeachingMode=(next:Mode)=>{setMode(next);setPlaying(false);setFrame(next==='ANATOMY'||next==='ALL'||next==='MECHANISM'?1:110);setOrgan('all');setView('front');if(next==='LOCAL')setHormone('SOMATOSTATIN');if(next==='FASTING')setHormone('MOTILIN');if(next==='MECHANISM'&&['GHRELIN','MOTILIN','SOMATOSTATIN','SEROTONIN'].includes(hormone))setHormone('GLP1')};
 const chooseHormone=(key:string)=>{setHormone(key);setOrgan('all');if(mode==='ALL'||mode==='ANATOMY'||mode==='COMPARE')setMode('ATLAS');if(mode==='MECHANISM'||mode==='LOCAL'){if(['GHRELIN','MOTILIN'].includes(key))setMode('FASTING');else if(['SOMATOSTATIN','SEROTONIN'].includes(key))setMode('LOCAL');else setMode('MECHANISM')}};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool||!atlas)return;const lifecycle=new AbortController();const register=(tool:any)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};const sync=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
 register({name:'configure_gi_teaching',description:'Select a teaching view, hormone and visible layers in the GI model.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:modes.map(m=>m.key)},hormone:{type:'string',enum:Object.keys(atlas.hormones)},layers:{type:'object',properties:Object.fromEntries(Object.keys(initialLayers).map(k=>[k,{type:'boolean'}])),additionalProperties:false}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['mode','hormone','layers'].includes(k)))throw Error('Invalid configuration');if(input.mode&&!modes.some(m=>m.key===input.mode))throw Error('Unknown view');if(input.hormone&&!atlas.hormones[input.hormone])throw Error('Unknown hormone');if(input.layers&&(typeof input.layers!=='object'||Object.entries(input.layers).some(([k,v])=>!(k in initialLayers)||typeof v!=='boolean')))throw Error('Invalid layers');let selected=input.hormone||hormone,next=input.mode||mode;if(next==='LOCAL'&&!['SOMATOSTATIN','SEROTONIN'].includes(selected))selected='SOMATOSTATIN';if(next==='FASTING')selected='MOTILIN';if(next==='MECHANISM'&&['GHRELIN','MOTILIN','SOMATOSTATIN','SEROTONIN'].includes(selected))selected='GLP1';setMode(next);setHormone(selected);setOrgan('all');setView('front');setPlaying(false);if(input.layers)setLayers(v=>({...v,...input.layers}));await sync();return{mode:next,hormone:selected,layers:{...layers,...input.layers}}}});
 register({name:'set_gi_timeline',description:'Pause or play the 180-frame Blender teaching sequence and scrub to an exact frame.',inputSchema:{type:'object',properties:{frame:{type:'number',minimum:1,maximum:180},playing:{type:'boolean'}},required:['frame'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||typeof input.frame!=='number'||!Number.isFinite(input.frame)||input.frame<1||input.frame>180||(input.playing!==undefined&&typeof input.playing!=='boolean'))throw Error('Frame must be between 1 and 180');setFrame(input.frame);setPlaying(input.playing??false);await sync();return{frame:input.frame,playing:input.playing??false}}});return()=>lifecycle.abort()
 },[atlas,mode,hormone,layers]);
 const h=atlas?.hormones[hormone],note=notes[mode],isAnimation=!['ANATOMY','ALL'].includes(mode);const stageStep=frame<40?0:frame<65?1:frame<85?2:frame<135?3:4;
 const stepNames=mode==='LOCAL'?['Local cue','Cell activation','Signal release','Local / neural route','Target response']:[hormone==='SECRETIN'?'Luminal acid':'Luminal nutrients','Cell sensing','Basolateral release','Signal transport','Target response'];
 return <main><a className="skip-model" href="#model" onClick={event=>{event.preventDefault();scrollToModel()}}>Skip to teaching model</a><header className="masthead"><span className="masthead-title">GI hormones</span><span className="folio">ANATOMY / PHYSIOLOGY</span><Sources/></header>
 <section className="opening"><div className="opening-title"><span className="eyebrow">THE TEACHING MODEL</span><h1>After a meal,<br/><span>a cascade begins.</span></h1><p className="opening-deck">Start with a representative GLP-1 pathway: follow a cue from the intestinal lumen through hormone release to a target response. Then explore the other cells and signals.</p></div><div className="specimen-collage"><figure className="specimen-photo"><img src="/assets/mucosa.jpg" alt="Normal small-intestinal mucosa with villi"/><figcaption>SMALL-INTESTINAL MUCOSA / MICROGRAPH</figcaption></figure><div className="specimen-note"><span className="handwritten">It starts in<br/>the epithelium.</span><ArrowDown size={28}/></div></div></section>
 <Tabs value={mode} onValueChange={v=>setTeachingMode(v as Mode)} className="view-tabs"><TabsList aria-label="Teaching views">{modes.map(m=><TabsTrigger key={m.key} value={m.key}><span>{m.number}</span>{m.label}</TabsTrigger>)}</TabsList><TabsContent value={mode}>
 <section className="workbench" id="model" tabIndex={-1} aria-label="Teaching model and study notes"><div className="model-column"><div className="stage" data-mode={mode}><div className="stage-heading"><span>{modes.find(m=>m.key===mode)?.label.toUpperCase()} <i>/</i> {mode==='ALL'?'ALL POPULATIONS':mode==='ANATOMY'?'WHOLE TRACT':mode==='FASTING'?'MOTILIN + GHRELIN':mode==='COMPARE'?'GIP + GLP-1':h?.display||hormone}</span><div className="stage-actions"><button className="reading-toggle" aria-pressed={textMode} onClick={()=>textMode?retryModel():openReading()}>{textMode?'Show 3D':'Reading view'}</button><button aria-label="Expand model" title="Expand model" onClick={()=>{const el=document.querySelector('.model-column');if(document.fullscreenElement)document.exitFullscreen();else el?.requestFullscreen?.()}}><Maximize2 size={18}/></button></div></div>
 {error?<div className="model-loading" role="alert"><p>The teaching data could not load.</p><button onClick={()=>location.reload()}>Retry</button></div>:atlas&&teaching?textMode?<div className="reading-scene" aria-label="Text teaching view" aria-live="polite">
 <span className="reading-kicker">{mode==='MECHANISM'||mode==='LOCAL'?`SEQUENCE / 0${stageStep+1}`:'TEACHING NOTES'}</span>
 <h2>{mode==='MECHANISM'&&hormone==='GLP1'?glpJourney[stageStep].title:notes[mode].title}</h2>
 <p>{mode==='MECHANISM'&&hormone==='GLP1'?glpJourney[stageStep].body:notes[mode].body}</p>
 {h&&!['ANATOMY','ALL','COMPARE'].includes(mode)&&<dl><div><dt>SOURCE</dt><dd>{cellNames[h.cell]} · {h.distribution}</dd></div><div><dt>TARGETS</dt><dd>{h.targets.map(t=>targetNames[t]||t).join(' · ')}</dd></div></dl>}
 {mode==='MECHANISM'&&hormone==='GLP1'&&<div className="reading-sources"><a href="https://pubmed.ncbi.nlm.nih.gov/35629924/" target="_blank" rel="noreferrer">Nutrient sensing ↗</a><a href="https://pubmed.ncbi.nlm.nih.gov/26571400/" target="_blank" rel="noreferrer">Islet response ↗</a></div>}
 <p className="reading-help">{['MECHANISM','LOCAL'].includes(mode)?'Use the sequence steps below to move at your own pace.':'The study note and hormone reference remain available below.'}</p>
 {modelError&&<div className="reading-error" role="status"><span>{modelError} The notes remain available.</span><button onClick={retryModel}>Retry 3D</button></div>}
 </div>:<Suspense fallback={<div className="model-loading" role="status">Loading the 3D renderer…</div>}><AnatomyViewer atlas={atlas} teaching={teaching} hormone={hormone} mode={mode} layers={layers} frame={frame} organ={organ} view={view} onPick={setOrgan} onReady={()=>setReady(true)} onError={message=>{setModelError(message);openReading()}}/></Suspense>:<div className="model-loading" role="status">Loading teaching data…</div>}
 {!textMode&&['ANATOMY','ATLAS','ALL','FASTING'].includes(mode)&&<div className="camera-bar" aria-label="Camera controls">{[['front','Front'],['quarter','¾ view'],['side','Side']].map(([k,v])=><button key={k} aria-pressed={view===k} onClick={()=>setView(k)}>{v}</button>)}<button title="Reset camera" aria-label="Reset camera" onClick={()=>{setView('reset-'+Date.now());setOrgan('all')}}><RotateCcw size={15}/></button></div>}
 <div className="stage-foot"><span>{textMode?'Read, then explore the study notes':['MECHANISM','LOCAL','COMPARE'].includes(mode)?'Scroll or pinch to zoom':'Drag to rotate · Pinch or scroll to zoom'}</span><span>{textMode?'READING VIEW':ready?'BLENDER SCENE':'LOADING'}</span></div></div>
 <div className="timeline" aria-label="Animation playback"><button className="play-button" aria-label={playing?'Pause animation':'Play animation'} disabled={!ready||textMode||!isAnimation} onClick={()=>{if(frame>=180)setFrame(1);setPlaying(!playing)}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button className="frame-edge" aria-label="First frame" disabled={!isAnimation} onClick={()=>{setFrame(1);setPlaying(false)}}><ChevronsLeft size={18}/></button><div className="timeline-range"><Slider ref={el=>{el?.querySelector('[role="slider"]')?.setAttribute('aria-label','Animation frame')}} min={1} max={180} step={1} value={[Math.round(frame)]} disabled={!isAnimation} onValueChange={v=>{setPlaying(false);setFrame(v[0])}}/><div className="timeline-marks"><span>01</span><span>{isAnimation?(mode==='FASTING'?'Migrating motor activity':mode==='COMPARE'?'Matched glucose comparison':mode==='ATLAS'?(frame<65?'Source signal':frame<135?'Signal transport':'Target response'):stepNames[stageStep]):'Choose a teaching sequence to play'}</span><span>180</span></div></div><button className="frame-edge" aria-label="Last frame" disabled={!isAnimation} onClick={()=>{setFrame(180);setPlaying(false)}}><ChevronsRight size={18}/></button><output aria-label="Current animation frame">{Math.round(frame).toString().padStart(3,'0')}<small> / 180</small></output><Select value={speed} onValueChange={setSpeed}><SelectTrigger aria-label="Playback speed" className="speed-select"><SelectValue/></SelectTrigger><SelectContent>{['0.5','1','2'].map(v=><SelectItem key={v} value={v}>{v}×</SelectItem>)}</SelectContent></Select><div className="loop-control"><label htmlFor="loop">Loop</label><Switch id="loop" checked={loop} onCheckedChange={setLoop}/></div></div>
 {['MECHANISM','LOCAL'].includes(mode)&&<div className="sequence-steps">{stepNames.map((name,i)=><button key={name} aria-current={stageStep===i?'step':undefined} onClick={()=>{setFrame([1,40,65,100,145][i]);setPlaying(false)}}><span>0{i+1}</span>{name}</button>)}</div>}
 {!textMode&&mode==='MECHANISM'&&hormone==='GLP1'&&<div className="journey-note" aria-live={playing?'off':'polite'}><span className="journey-index">FIELD NOTE / 0{stageStep+1}</span><div><h3>{glpJourney[stageStep].title}</h3><p>{glpJourney[stageStep].body}</p></div><div className="journey-sources"><a href="https://pubmed.ncbi.nlm.nih.gov/35629924/" target="_blank" rel="noreferrer">Nutrient sensing ↗</a><a href="https://pubmed.ncbi.nlm.nih.gov/26571400/" target="_blank" rel="noreferrer">Islet response ↗</a></div></div>}
 {mode==='MECHANISM'&&hormone==='GLP1'&&<a className="lesson-return" href="#meal-check" onClick={e=>{e.preventDefault();const el=document.querySelector<HTMLElement>('#meal-check');el?.focus({preventScroll:true});el?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}}>Check your understanding ↓</a>}
 </div>
 <aside className="study-sheet"><div className="sheet-corner"/><div className="sheet-heading"><span className="eyebrow">{mode==='ATLAS'?'HORMONE RECORD':'STUDY NOTE'}</span><span className="sheet-number">{modes.find(m=>m.key===mode)?.number}</span></div>
 {mode==='ANATOMY'?<><h2>The anatomy</h2><p>{note.body}</p><label className="field-label" htmlFor="region">Isolate a region</label><Select value={organ} onValueChange={setOrgan}><SelectTrigger id="region" className="paper-select"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(organNames).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><div className="closeups"><button onClick={()=>{setView('stomach');setOrgan('stomach')}}>Stomach close-up <ArrowUpRight size={16}/></button><button onClick={()=>{setView('ileocecal');setOrgan('all')}}>Ileocecal junction <ArrowUpRight size={16}/></button></div></>:mode==='ALL'?<><h2>Cell populations</h2><p>{note.body}</p><div className="population-list">{atlas&&Array.from(new Set(Object.values(atlas.hormones).map(h=>h.cell))).map(cell=>{const items=Object.entries(atlas.hormones).filter(([,h])=>h.cell===cell);return <button key={cell} onClick={()=>{setTeachingMode('ATLAS');setHormone(items[0][0])}}><span className="cell-symbol" style={{background:`rgb(${items[0][1].color.map(c=>c*255).join(',')})`}}>{cell==='Enterochromaffin'?'EC':cell}</span><span>{items.map(([,h])=>h.display||Object.keys(atlas.hormones).find(k=>atlas.hormones[k]===h)).join(' · ')}</span><ChevronRight size={14}/></button>})}</div></>:mode==='COMPARE'?<><h2>Oral vs IV</h2><p>{note.body}</p><div className="comparison-key"><span><i className="oral-line"/>Oral glucose</span><span><i className="iv-line"/>IV glucose</span></div><div className="margin-note handwritten">Match the glucose.<br/>Compare the insulin.</div><p className="fine-print">The curves are normalized illustrations, not patient data. GIP and GLP-1 are the two incretins.</p></>:<><label className="field-label" htmlFor="hormone">{mode==='FASTING'?'Inspect a fasting hormone':'Choose a hormone'}</label><Select value={hormone} onValueChange={chooseHormone}><SelectTrigger id="hormone" className="paper-select hormone-select"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(atlas?.hormones||{}).filter(([k])=>mode==='LOCAL'?['SOMATOSTATIN','SEROTONIN'].includes(k):mode==='FASTING'?['MOTILIN','GHRELIN'].includes(k):true).map(([k,h])=><SelectItem key={k} value={k}>{h.display||k}</SelectItem>)}</SelectContent></Select>{h&&<><div className="record-title"><h2>{h.display||hormone}</h2>{h.incretin&&<span className="incretin-stamp">INCRETIN</span>}</div><p className="function-copy">{h.role}.</p><dl className="hormone-facts"><dt>SOURCE</dt><dd>{cellNames[h.cell]}<small>{h.distribution}</small></dd><dt>TARGETS</dt><dd>{h.targets.map(t=><span className="target-word" key={t}>{targetNames[t]||t}</span>)}</dd></dl>{mode!=='ATLAS'&&<p className="mode-note">{note.body}</p>}</>}</>}
 <div className="layers-block"><button className="layer-heading" aria-expanded={layerPanel} onClick={()=>setLayerPanel(!layerPanel)}><SlidersHorizontal size={16}/>Model layers<span>{layerPanel?'−':'+'}</span></button>{layerPanel&&<div className="layer-list">{Object.entries(layers).map(([k,v])=><div key={k}><label htmlFor={'layer-'+k}>{k==='CellTypes'?'Cell populations':k==='Hormones'?'Signals & pathways':k==='Targets'?'Target organs':k==='Annotations'?'Labels':k}</label><Switch id={'layer-'+k} checked={v} onCheckedChange={checked=>setLayers(old=>({...old,[k]:checked}))}/></div>)}</div>}</div>
 <p className="handwritten sheet-note">{note.note}</p><p className="fine-print">Cell density, signal timing and response size are qualitative.</p>
 </aside></section></TabsContent></Tabs>
 <MealCheck onReview={step=>{setMode('MECHANISM');setHormone('GLP1');setOrgan('all');setView('front');setPlaying(false);setFrame([1,40,65,100,145][step]);scrollToModel()}}/>
 <section className="reference-strip"><div><span className="eyebrow">ALL TWELVE HORMONES</span><h2>The hormone reference.</h2></div><Dialog><DialogTrigger className="ledger-trigger">Open the hormone table <ArrowUpRight size={20}/></DialogTrigger><DialogContent className="ledger-dialog"><DialogTitle>Hormones, source cells & targets</DialogTitle><DialogDescription>The full biology table retained from the original teaching brief.</DialogDescription><div className="ledger-scroll"><Table><TableHeader><TableRow><TableHead>Hormone</TableHead><TableHead>Source</TableHead><TableHead>Function</TableHead><TableHead>Targets</TableHead></TableRow></TableHeader><TableBody>{Object.entries(atlas?.hormones||{}).map(([k,h])=><TableRow key={k}><TableCell><DialogClose asChild><button onClick={()=>{chooseHormone(k);setMode('ATLAS')}}>{h.display||k}</button></DialogClose>{h.incretin&&<small>Incretin</small>}</TableCell><TableCell>{cellNames[h.cell]}<small>{h.distribution}</small></TableCell><TableCell>{h.role}</TableCell><TableCell>{h.targets.map(t=>targetNames[t]||t).join(', ')}</TableCell></TableRow>)}</TableBody></Table></div></DialogContent></Dialog></section>
 <section className="study-board"><article className="meal-study"><figure><img src="/assets/meal.jpg" alt="A plant-based meal photographed by Ella Olsson"/><figcaption className="handwritten">After a meal…</figcaption></figure><div className="meal-copy"><span className="eyebrow">FED STATE</span><h2>Sensing.<br/>Secretion.<br/>Response.</h2><p>Follow the sequence from the luminal cue to the target response.</p><button onClick={()=>{setTeachingMode('MECHANISM');setFrame(1);scrollToModel()}}>Open secretion sequence <ArrowUpRight size={17}/></button></div></article><article className="fasting-study"><span className="eyebrow">FASTING STATE</span><h2>Between<br/>meals.</h2><p>Motilin’s migrating motor activity and ghrelin’s pre-meal hunger signal have their own teaching view.</p><span className="handwritten">Watch the wave.</span><button onClick={()=>{setTeachingMode('FASTING');setFrame(1);scrollToModel()}}>Open fasting sequence <ArrowUpRight size={17}/></button></article></section>
 <footer><span>GI hormones / teaching model</span><Sources/><a href="/assets/photo-credit.txt" target="_blank">Photo credits</a></footer></main>
}
