'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
export type Marker={position:number[];keys:string;cell:string};
export default function AnatomyViewer({markers,hormone,color,showCells,organ,view,playing,paths,connections,onPick}:{paths:Record<string,number[][]>;connections:boolean;markers:Marker[];hormone:string;color:number[];showCells:boolean;organ:string;view:string;playing:boolean;onPick:(s:string)=>void}){
 const host=useRef<HTMLDivElement>(null),api=useRef<any>(null),props=useRef({hormone,color,showCells,organ,playing,connections,onPick});props.current={hormone,color,showCells,organ,playing,connections,onPick};const[status,setStatus]=useState('Loading the 3D anatomy…');
 useEffect(()=>{if(!host.current)return;let disposed=false,frame=0;const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setStatus('3D is unavailable in this browser. The anatomy reference image is shown below.');return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive gastrointestinal anatomy. Drag to rotate; scroll or pinch to zoom.');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,300);camera.position.set(0,5,76);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,4,0);controls.enableDamping=true;controls.minDistance=22;controls.maxDistance=105;controls.enablePan=true;
 scene.add(new THREE.HemisphereLight(0xfff8ef,0x657480,2));const key=new THREE.DirectionalLight(0xffe9d2,3);key.position.set(-20,30,40);scene.add(key);const fill=new THREE.DirectionalLight(0xd9ebff,2);fill.position.set(20,10,-25);scene.add(fill);
 const cells=new THREE.Group(),routes=new THREE.Group();scene.add(cells,routes);let particles:{mesh:THREE.Mesh;curve:THREE.CatmullRomCurve3}[]=[];let routeTime=0,lastTime=0;const geo=new THREE.SphereGeometry(.16,8,6),mat=new THREE.MeshBasicMaterial({color:0xf5c24b});let mesh:THREE.InstancedMesh|null=null;let anatomy:THREE.Group|null=null;
 new GLTFLoader().load('/assets/anatomy.glb',g=>{if(disposed)return;anatomy=g.scene;scene.add(anatomy);anatomy.traverse(o=>{if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshStandardMaterial;m.roughness=.65;m.metalness=0;o.userData.originalColor=m.color.clone();}});setStatus('');},undefined,()=>setStatus('The 3D file could not load. Refresh to try again.'));
 const resize=()=>{if(!el.clientWidth||!el.clientHeight)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};const obs=new ResizeObserver(resize);obs.observe(el);resize();
 const ray=new THREE.Raycaster();let down=[0,0];const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY]};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||!anatomy)return;const r=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObject(anatomy,true)[0];if(hit){const name=hit.object.name;const organ=['stomach','duodenum','jejunum','ileum','colon','esophagus'].find(s=>name.includes(s));if(organ)props.current.onPick(organ);}};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',click);
 api.current={camera,controls,updatePaths:(entries:[string,number[][]][])=>{routes.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();(o.material as THREE.Material).dispose()}if(o instanceof THREE.Sprite){o.material.map?.dispose();o.material.dispose()}});routes.clear();particles=[];entries.forEach(([key,points])=>{const pts=points.map(p=>new THREE.Vector3(p[0],p[2],-p[1]));const curve=new THREE.CatmullRomCurve3(pts);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(60)),new THREE.LineBasicMaterial({color:0x47684b,transparent:true,opacity:.65}));routes.add(line);const dot=new THREE.Mesh(new THREE.SphereGeometry(.22,10,8),new THREE.MeshBasicMaterial({color:0x355e3b}));routes.add(dot);particles.push({mesh:dot,curve});const end=pts[pts.length-1];const canvas=document.createElement("canvas");canvas.width=512;canvas.height=110;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#f8f7ee";ctx.fillRect(0,0,512,110);ctx.fillStyle="#283e30";ctx.font="42px Arial";ctx.textAlign="center";ctx.fillText(key.split("|")[1].replaceAll("_"," "),256,70);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false}));sprite.position.copy(end);sprite.position.y+=.8;sprite.scale.set(8,1.72,1);routes.add(sprite);})},updateMarkers:(list:Marker[])=>{if(mesh){cells.remove(mesh);mesh.dispose()}mesh=new THREE.InstancedMesh(geo,mat,list.length);const matrix=new THREE.Matrix4();list.forEach((m,i)=>{matrix.makeTranslation(...m.position as [number,number,number]);mesh!.setMatrixAt(i,matrix)});cells.add(mesh)},setView:(v:string)=>{const positions:Record<string,number[]>={front:[0,5,76],quarter:[40,14,65],side:[74,6,0],stomach:[14,20,33],ileocecal:[-14,-7,30]};const p=positions[v]||positions.front;camera.position.set(...p as [number,number,number]);controls.target.set(v==='stomach'?3:v==='ileocecal'?-6:0,v==='stomach'?14:v==='ileocecal'?-6:4,0);controls.update()}};
 const animate=(t:number)=>{frame=requestAnimationFrame(animate);controls.update();if(props.current.playing)routeTime+=(t-lastTime)*.00012;lastTime=t;routes.visible=props.current.connections;particles.forEach((p,i)=>p.mesh.position.copy(p.curve.getPointAt((routeTime+i*.17)%1)));cells.visible=props.current.showCells;mat.color.setRGB(...props.current.color as [number,number,number]);const pulse=props.current.playing?1+.12*Math.sin(t*.004):1;cells.scale.setScalar(1);mat.opacity=pulse; if(anatomy)anatomy.traverse(o=>{if(o instanceof THREE.Mesh){const selected=props.current.organ==='all'||o.name.includes(props.current.organ)||(props.current.organ==='colon'&&/taenia|epiploic/.test(o.name));const m=o.material as THREE.MeshStandardMaterial;m.transparent=!selected;m.opacity=selected?1:.13;m.depthWrite=selected;}});renderer.render(scene,camera)};frame=requestAnimationFrame(animate);
 return()=>{disposed=true;cancelAnimationFrame(frame);obs.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});renderer.dispose();el.removeChild(renderer.domElement);api.current=null};
 },[]);
 useEffect(()=>{api.current?.updateMarkers(markers.filter(m=>m.keys.split(',').includes(hormone)))},[markers,hormone]);
 useEffect(()=>{api.current?.setView(view)},[view]);
 useEffect(()=>{api.current?.updatePaths(Object.entries(paths).filter(([key])=>key.startsWith(hormone+'|')))},[paths,hormone]);
 useEffect(()=>{if(connections&&api.current){api.current.camera.position.set(-8,5,85);api.current.controls.target.set(-7,4,0)}else api.current?.setView(view)},[connections]);
 return <div className="viewer-wrap"><div ref={host} className="three-view"/>{status&&<div className="model-loading"><img src="/assets/anatomy-preview.png" alt="Three-quarter anatomical reference"/><p role="status">{status}</p></div>}</div>
}
